### ISSUE TITLE
Store queries in ETS table

### ISSUE THREAD

**Issue by tsloughter** [artemeff/eql#3]
I'm going to use this by seeding an ets table with the queries instead of looking them up from the list.

I thought I'd check if you'd be interested in this being a core feature, and I can send a PR, or if I should just keep it in my application.

**Comment by artemeff** [comment]
It would be cool!

**Comment by tsloughter** [comment]
Great, I opened a PR. I've only just started playing with this so still trying to work out what a good api and flow is for it. I'll close this issue though.
